/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.landoop;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Avro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7803254121436574976L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avro\",\"namespace\":\"com.landoop\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"letter\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avro> ENCODER =
      new BinaryMessageEncoder<Avro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avro> DECODER =
      new BinaryMessageDecoder<Avro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Avro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Avro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Avro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Avro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Avro from a ByteBuffer. */
  public static Avro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer id;
  @Deprecated public java.lang.CharSequence letter;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param letter The new value for letter
   */
  public Avro(java.lang.Integer id, java.lang.CharSequence letter) {
    this.id = id;
    this.letter = letter;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return letter;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: letter = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'letter' field.
   * @return The value of the 'letter' field.
   */
  public java.lang.CharSequence getLetter() {
    return letter;
  }

  /**
   * Sets the value of the 'letter' field.
   * @param value the value to set.
   */
  public void setLetter(java.lang.CharSequence value) {
    this.letter = value;
  }

  /**
   * Creates a new Avro RecordBuilder.
   * @return A new Avro RecordBuilder
   */
  public static com.landoop.Avro.Builder newBuilder() {
    return new com.landoop.Avro.Builder();
  }

  /**
   * Creates a new Avro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avro RecordBuilder
   */
  public static com.landoop.Avro.Builder newBuilder(com.landoop.Avro.Builder other) {
    return new com.landoop.Avro.Builder(other);
  }

  /**
   * Creates a new Avro RecordBuilder by copying an existing Avro instance.
   * @param other The existing instance to copy.
   * @return A new Avro RecordBuilder
   */
  public static com.landoop.Avro.Builder newBuilder(com.landoop.Avro other) {
    return new com.landoop.Avro.Builder(other);
  }

  /**
   * RecordBuilder for Avro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avro>
    implements org.apache.avro.data.RecordBuilder<Avro> {

    private java.lang.Integer id;
    private java.lang.CharSequence letter;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.landoop.Avro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.letter)) {
        this.letter = data().deepCopy(fields()[1].schema(), other.letter);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Avro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.landoop.Avro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.letter)) {
        this.letter = data().deepCopy(fields()[1].schema(), other.letter);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.landoop.Avro.Builder setId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.landoop.Avro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'letter' field.
      * @return The value.
      */
    public java.lang.CharSequence getLetter() {
      return letter;
    }

    /**
      * Sets the value of the 'letter' field.
      * @param value The value of 'letter'.
      * @return This builder.
      */
    public com.landoop.Avro.Builder setLetter(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.letter = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'letter' field has been set.
      * @return True if the 'letter' field has been set, false otherwise.
      */
    public boolean hasLetter() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'letter' field.
      * @return This builder.
      */
    public com.landoop.Avro.Builder clearLetter() {
      letter = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avro build() {
      try {
        Avro record = new Avro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.letter = fieldSetFlags()[1] ? this.letter : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avro>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avro>
    READER$ = (org.apache.avro.io.DatumReader<Avro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
